package com.proaut.claudeshim;

/**
 * Build-time metadata. Constants are generated by Gradle at build time
 * ({@code BuildInfoConstants}) so the info is available even in GraalVM
 * native images where the classpath properties file is stripped.
 */
final class BuildInfo {

    private final String version;
    private final String date;
    private final String branch;

    private BuildInfo(String version, String date, String branch) {
        this.version = version;
        this.date = date;
        this.branch = branch;
    }

    /**
     * Return a {@link BuildInfo} with the build-time constants.
     * Never returns {@code null}.
     */
    static BuildInfo load() {
        return new BuildInfo(
                BuildInfoConstants.VERSION,
                BuildInfoConstants.DATE,
                BuildInfoConstants.BRANCH
        );
    }

    String version() { return version; }
    String date()    { return date; }
    String branch()  { return branch; }

    @Override
    public String toString() {
        return String.format("claude-shim %s (build %s, branch %s)", version, date, branch);
    }
}
